# Generated by Django 4.2.9 on 2024-01-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='О компании')),
                ('img', models.ImageField(upload_to='about/', verbose_name='фотки')),
                ('desc', models.TextField(verbose_name='описание')),
            ],
        ),
    ]
