# Generated by Django 5.0.1 on 2024-01-13 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название')),
                ('img', models.ImageField(upload_to='product/', verbose_name='фотки')),
                ('desc', models.TextField(verbose_name='описание')),
                ('price', models.FloatField(verbose_name='цена')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.category')),
            ],
        ),
    ]
