# Generated by Django 5.0.1 on 2024-01-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='имя')),
                ('surname', models.TextField(verbose_name='фамилия')),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
