# Generated by Django 5.0.1 on 2024-01-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_proabout_delete_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proabout',
            name='name',
        ),
        migrations.RemoveField(
            model_name='proabout',
            name='surname',
        ),
    ]
