# Generated by Django 5.0.1 on 2024-01-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_product_desc_alter_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorypage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marc', models.CharField(max_length=30, verbose_name='марка авто')),
                ('modelavto', models.TextField(verbose_name='модель')),
                ('godvypuska', models.FloatField(verbose_name='год выпуска')),
                ('dvigatel', models.FloatField(verbose_name='объем двигаетля')),
                ('price', models.FloatField(verbose_name='цена в $')),
            ],
        ),
    ]
