# Generated by Django 5.0.1 on 2024-01-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_proabout_name_remove_proabout_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='proabout',
            name='desc',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='proabout',
            name='img',
            field=models.ImageField(null=True, upload_to='product/', verbose_name='фотки'),
        ),
        migrations.AddField(
            model_name='proabout',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='proabout',
            name='price',
            field=models.FloatField(null=True, verbose_name='цена'),
        ),
    ]
