# Generated by Django 5.0.1 on 2024-01-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_marc_kategorypage_marc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategorypage',
            name='dvigatel',
            field=models.FloatField(blank=True, null=True, verbose_name='объем двигаетля'),
        ),
        migrations.AddField(
            model_name='kategorypage',
            name='godvypuska',
            field=models.FloatField(blank=True, null=True, verbose_name='год выпуска'),
        ),
        migrations.AddField(
            model_name='kategorypage',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='kategory/', verbose_name='изображение'),
        ),
        migrations.AddField(
            model_name='kategorypage',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='цена в $'),
        ),
        migrations.AlterField(
            model_name='kategorypage',
            name='marc',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='марка авто'),
        ),
        migrations.AlterField(
            model_name='kategorypage',
            name='modelavto',
            field=models.TextField(blank=True, null=True, verbose_name='модель'),
        ),
    ]
