# Generated by Django 5.0.1 on 2024-01-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_proabout_desc_proabout_img_proabout_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proabout',
            name='img',
        ),
    ]
