# Generated by Django 5.0.1 on 2024-01-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_proabout_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proabout',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='proabout',
            name='name',
        ),
        migrations.RemoveField(
            model_name='proabout',
            name='price',
        ),
    ]
