# Generated by Django 4.2.9 on 2024-02-16 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_kategorypage_dvigatel_kategorypage_godvypuska_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='gallery/')),
                ('pageAbout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.aboutpage')),
            ],
        ),
    ]
