# Generated by Django 4.2.9 on 2024-02-16 14:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
