# Generated by Django 4.2.9 on 2024-02-16 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_aboutpage_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='название марки')),
                ('url', models.SlugField(max_length=130, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='год выпуска')),
                ('url', models.SlugField(max_length=130, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Kategorypage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='dvigatel',
            field=models.FloatField(blank=True, null=True, verbose_name='объем двигаетля'),
        ),
        migrations.AddField(
            model_name='product',
            name='godvypuska',
            field=models.FloatField(blank=True, null=True, verbose_name='год выпуска'),
        ),
        migrations.AddField(
            model_name='product',
            name='modelavto',
            field=models.TextField(blank=True, null=True, verbose_name='модель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='цена в $'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='product',
            name='marka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.marka'),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.year'),
        ),
    ]
