# Generated by Django 4.2.9 on 2024-02-17 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_marka_year_delete_kategorypage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'о нас', 'verbose_name_plural': 'Страница "О нас"'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='marka',
            options={'verbose_name': 'марка', 'verbose_name_plural': 'Марки'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'авто', 'verbose_name_plural': 'Авто'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'verbose_name': 'год', 'verbose_name_plural': 'Год'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='godvypuska',
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dvigatel',
            field=models.FloatField(blank=True, null=True, verbose_name='объем двигателя'),
        ),
        migrations.AlterField(
            model_name='product',
            name='marka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.marka', verbose_name='марка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=70, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.year', verbose_name='год выпуска'),
        ),
    ]
