# Generated by Django 4.2.9 on 2024-02-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_otzyvy_alter_aboutpage_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otzyvy',
            options={'verbose_name': 'написать отзыв', 'verbose_name_plural': 'Отзыв на страницу'},
        ),
        migrations.AlterField(
            model_name='otzyvy',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='написать отзыв'),
        ),
        migrations.AlterField(
            model_name='otzyvy',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Тема отзыва'),
        ),
    ]
