# Generated by Django 4.2.9 on 2024-02-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_otzyvy_options_alter_otzyvy_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otzyvy',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Ваше имя'),
        ),
    ]
